name: CI-build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - LICENSE
  workflow_dispatch:

jobs:
  windows:
    strategy:
      matrix:
        os-version: ['x64']

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: fetch VSET-core # fetch VSET-core from https://github.com/TensoRaws/VSET-core/releases
        run: |
          cd resources
          $baseUrl = "https://github.com/TensoRaws/VSET-core/releases/download/v4.2-0819"
          1..5 | ForEach-Object {
              $url = "$baseUrl/VSET-core.7z.00$_"
              Write-Host "Downloading $url ..."
              Invoke-WebRequest -Uri $url -OutFile "VSET-core.7z.00$_"
          }
          7z x VSET-core.7z.001 -oVSET-core -y
          Remove-Item VSET-core.7z.*

      - name: build
        run: |
          pnpm install
          pnpm run build:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: zip-unpacked-x64
        if: matrix.os-version == 'x64'
        run: |
          cd .\dist\win-unpacked
          7z a -r Final2x-windows-${{ matrix.os-version }}-unpacked.7z *

      - name: upload-unpacked-x64
        if: matrix.os-version == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: Final2x-windows-${{ matrix.os-version }}-unpacked
          path: dist/win-unpacked/*.7z
